import { Outfit } from 'next/font/google';
import "./globals.css";

const anton = Outfit({
  subsets: ['latin'],
weight:"500"});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"         >
      <body
className={`${anton.className}`}
      >
        {/*font-norline font-bold  */}
        {children}
      </body>
    </html>
  );
}
